// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxN-g-Be9DZG4zuYBpkLp-UFG3aRqmU0I',
    appId: '1:975313431769:web:8285890d8fff4541d0e2c8',
    messagingSenderId: '975313431769',
    projectId: 'chatbot-540cb',
    authDomain: 'chatbot-540cb.firebaseapp.com',
    storageBucket: 'chatbot-540cb.firebasestorage.app',
    measurementId: 'G-DRH2JXFLGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ4YPRcIf9jEpjvAj-FPN7yDAnCfHmm04',
    appId: '1:975313431769:android:9e64c24121eddc41d0e2c8',
    messagingSenderId: '975313431769',
    projectId: 'chatbot-540cb',
    storageBucket: 'chatbot-540cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPmHfa3QT0AF7KBFiSeRLsQg1BbSC-eKw',
    appId: '1:975313431769:ios:a006e22ba61aad10d0e2c8',
    messagingSenderId: '975313431769',
    projectId: 'chatbot-540cb',
    storageBucket: 'chatbot-540cb.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPmHfa3QT0AF7KBFiSeRLsQg1BbSC-eKw',
    appId: '1:975313431769:ios:a006e22ba61aad10d0e2c8',
    messagingSenderId: '975313431769',
    projectId: 'chatbot-540cb',
    storageBucket: 'chatbot-540cb.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxN-g-Be9DZG4zuYBpkLp-UFG3aRqmU0I',
    appId: '1:975313431769:web:e655ef9d1858b027d0e2c8',
    messagingSenderId: '975313431769',
    projectId: 'chatbot-540cb',
    authDomain: 'chatbot-540cb.firebaseapp.com',
    storageBucket: 'chatbot-540cb.firebasestorage.app',
    measurementId: 'G-SQ01EJWD0W',
  );
}
